### ISSUE TITLE
Trouble building?

### ISSUE THREAD

**Issue by mikecico** [oracle/crashcart#2]
I cloned the project locally, and had issues building:

> fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
> ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
> 
> WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
> ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: temporary error (try again later)
> WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
> 

I did some debugging, trying to hack around the build a bit, but could only get so far:

> checking whether DBD::SQLite works... configure: error: in `/nix-1.11.6':
> configure: error: The Perl module WWW::Curl is missing.
> See `config.log' for more details
> 

For some reason I had to make local changes to the Dockerfile to even get that far, even though it looked like it should have worked as-is:

diff --git a/builder/Dockerfile b/builder/Dockerfile
index f76f539..14974ba 100644
--- a/builder/Dockerfile
+++ b/builder/Dockerfile
@@ -9,7 +9,7 @@ RUN echo 'nixbld:x:998:nobody' >> /etc/group && \
         e2fsprogs e2fsprogs-extra && \
     apk add -U perl-www-curl --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ && \
     rm -rf /var/cache/apk/* && \
-    curl -O http://nixos.org/releases/nix/nix-${nversion}/nix-${nversion}.tar.bz2 && \
+    curl -O  https://nixos.org/releases/nix/nix-1.11.6/nix-1.11.6.tar.bz2 && \
     echo "${nsha}  nix-${nversion}.tar.bz2" | sha256sum -c && \
     tar -xjf nix-${nversion}.tar.bz2 && \
     sed -i '1i#include <string.h>' nix-${nversion}/src/libutil/affinity.cc && \

I had also hacked out the proxy settings, since I was trying to build this outside the Oracle network.

**Comment by tjfontaine** [comment]
The curl issue is it's missing `-L` seems like they require `https` now. I'll keep looking at it.
