### ISSUE TITLE
crashcart build hangs

### ISSUE THREAD

**Issue by prabhastechie** [oracle/crashcart#8]
I am trying to build oracle crashcart based on the following README:
https://github.com/oracle/crashcart

I have cloned the github repository and run build.sh first.
Now on running `build_image.sh` it runs smoothly for an hour and then hangs with the following message: 
`checking that generated files are newer than configure ...`
I am on Ubuntu 16.04 desktop, which has a kernel version 4.4, but not sure if that is the problem at the build stage itself.Any pointers?
-- | --

**Comment by vishvananda** [comment]
I've managed to reproduce this issue, but I do not have a solution yet. Not sure if this is a weird interaction with docker or alpine or kernel version.

**Comment by techyugadi** [comment]
could you tell me if it works on centos?

**Comment by vishvananda** [comment]
This issue should be fixed now. There seemed to be a problem with using Alpine as the builder. I'm not sure if this is a weird bash or musl bug, but calling wait on a pid that had already exited was causing the configure script to hang indefinitely. The builder uses Ubuntu now and completes.
